FROM  ubi8/ubi:latest
#
ENV   HTTPD_ROOT=/var/www/html
ENV   INPUT_PATH=src   
#
LABEL MAINTAINER='Sebastian Andreoletti ' \
      io.openshift.tags='do288,containerfile,s2i' \
      io.openshift.description='Prueba de containerfile ' \
      io.openshift.expose-services='8080,httpd'
#
RUN     yum install -y  httpd \
    &&  mkdir -p     /app/src-workdir  \
    &&  chgrp -R 0   /app/src-workdir  \
    &&  chmod -R g=u /app/src-workdir  \
    &&  echo '..env: '${HTTPD_ROOT}';\n INPUT-PATH: '${INPUT_PATH}';'  \
    &&  yum clean all -y
#
WORKDIR ${HTTPD_ROOT}
USER    root
#
ONBUILD  COPY  ${INPUT_PATH}  ./
ONBUILD  RUN   pwd && ls -lta ./

CMD ["/usr/sbin/httpd","-DFOREGROUND"]
